/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: abazibiz (https://sketchfab.com/abazibiz)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ibanez-jem-guitar-daeadd913644438aa3096bb357a02016
title: ibanez jem guitar
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials.lambert4SG} geometry={nodes.mesh_0.geometry} />
        <mesh material={materials.lambert5SG} geometry={nodes.mesh_1.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
